In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"parameters_8000-10000.csv")

In [3]:
df.drop(columns=[
    'player_101','player_102','player_104','player_105','player_113','player_115','player_116',
    'player_121','player_123','player_127','player_128','player_130','player_133','player_134',
    'player_136','player_138','player_14','player_144','player_145','player_146','player_148',
    'player_152','player_156','player_157','player_158','player_16','player_98','player_97',
    'player_90','player_96','player_88','player_86','player_78','player_74','player_73',
    'player_72','player_68','player_67','player_65','player_48','player_50','player_53',
    'player_54','player_55','player_57','player_58','player_161','player_165','player_166',
    'player_168','player_169','player_170','player_176','player_179','player_183','player_187',
    'player_19','player_2','player_23','player_37','player_43','player_44','player_45','player_33',
    'player_34','player_3','player_31','player_30','player_22','player_20','player_15','player_100','player_0',
    'player_80','player_8','player_82','player_83','player_87','player_89','player_92','player_93','player_94','player_99',
    'player_35','player_47','player_122','player_36','player_39','player_41','player_51',
    'player_59','player_62','player_64','player_66','player_76',
    'player_77','player_81','player_117','player_120','player_125','player_13','player_131','player_154',
    'player_167','player_172','player_24','player_21','player_28','player_29',
    'player_32','player_38','player_46','player_40','player_5','player_61',
    'player_84','player_95','player_12','player_18','player_27','player_4','player_91','seed','player_110','player_135','player_186',
    'player_149','player_182'
],inplace=True)

In [4]:
df.loc[df["player_42"] == "Grofman", "player_42"] = np.nan

In [5]:
df.loc[df["player_85"] == "Slow Tit For Two Tats", "player_85"] = np.nan

In [6]:
df.loc[df["player_164"] == "Evolved FSM 4", "player_164"] = np.nan

In [7]:
df.loc[df["player_164"] == "Evolved FSM 16", "player_164"] = np.nan

In [8]:
df.loc[df["player_160"] == "Evolved FSM 16", "player_160"] = np.nan

In [9]:
df.loc[df["player_75"] == "Cycler CCCDCD", "player_75"] = np.nan

In [10]:
pd.set_option("display.max_rows",None)

In [11]:
df = df.drop(df.index[100:182])

In [12]:
df.shape

(100, 66)

In [13]:
df.sample()

,noise,player_1,player_10,player_103,player_106,player_107,player_108,player_109,player_11,player_111,...,player_70,player_71,player_75,player_79,player_85,player_9,probend,repetitions,size,turns
86,0.892433,DoubleResurrection,Predator,Slow Tit For Two Tats 2,Grudger,Average Copier,Appeaser,Level Punisher,$\pi$,Hard Prober,...,Suspicious Tit For Tat,Raider,VeryBad,Prober 2,NaN,Alternator Hunter,0.083551,47.0,188.0,200.0

In [14]:
# created the    Highest_avg_score    AND    Winning _strategy columns by the code given below using axelrod library

In [15]:
# import axelrod as axl
# import numpy as np

# noise = 0.345832
# probend = 0.844851
# repetitions = 19
# turns = 141

# strategy_map ={
#     "DoubleResurrection": axl.DoubleResurrection,
#     "Predator": axl.Predator,
#     "SlowTitForTwoTats2": axl.SlowTitForTwoTats2,
#     "Grudger": axl.Grudger,
#     "AverageCopier": axl.AverageCopier,
#     "Appeaser": axl.Appeaser,
#     "LevelPunisher": axl.LevelPunisher,
#     "HardProber": axl.HardProber,
#     "SolutionB5": axl.SolutionB5,
#     "ThueMorse": axl.ThueMorse,
#     "TitForTat": axl.TitForTat,
#     "TrickyDefector": axl.TrickyDefector,
#     "Calculator": axl.Calculator,
#     "Bully": axl.Bully,
#     "Inverse": axl.Inverse,
#     "StochasticCooperator": axl.StochasticCooperator,
#     "NiceAverageCopier": axl.NiceAverageCopier,
#     "Winner12": axl.Winner12,
#     "Resurrection": axl.Resurrection,
#     "TitFor2Tats": axl.TitFor2Tats,
#     "RandomHunter": axl.RandomHunter,
#     "Thumper": axl.Thumper,
#     "SoftGrudger": axl.SoftGrudger,
#     "Prober": axl.Prober,
#     "TF1": axl.TF1,
#     "ForgetfulGrudger": axl.ForgetfulGrudger,
#     "Winner21": axl.Winner21,
#     "SelfSteem": axl.SelfSteem,
#     "TrickyCooperator": axl.TrickyCooperator,
#     "Negation": axl.Negation,
#     "ThueMorseInverse": axl.ThueMorseInverse,
#     "Aggravater": axl.Aggravater,
#     "Fortress4": axl.Fortress4,
#     "TF2": axl.TF2,
#     "DefectorHunter": axl.DefectorHunter,
#     "CyclerDDC": axl.CyclerDDC,
#     "Prober3": axl.Prober3,
#     "Defector": axl.Defector,
#     "ALLCorALLD": axl.ALLCorALLD,
#     "GrudgerAlternator": axl.GrudgerAlternator,
#     "MathConstantHunter": axl.MathConstantHunter,
#     "HardTitForTat": axl.HardTitForTat,
#     "Prober4": axl.Prober4,
#     "ForgivingTitForTat": axl.ForgivingTitForTat,
#     "BetterAndBetter": axl.BetterAndBetter,
#     "Desperate": axl.Desperate,
#     "HardTitFor2Tats": axl.HardTitFor2Tats,
#     "Gradual": axl.Gradual,
#     "EventualCycleHunter": axl.EventualCycleHunter,
#     "CyclerDC": axl.CyclerDC,
#     "TF3": axl.TF3,
#     "SuspiciousTitForTat": axl.SuspiciousTitForTat,
#     "Raider": axl.Raider,
#     "VeryBad": axl.VeryBad,
#     "Prober2": axl.Prober2,
#     "AlternatorHunter": axl.AlternatorHunter
# }

# strategy_names = list(strategy_map.keys())
# players = [strategy_map[name]() for name in strategy_names]

# tournament = axl.Tournament(
#     players=players,
#     turns=turns,
#     repetitions=repetitions,
#     noise=noise,
#     prob_end=probend
# )

# results = tournament.play()

# scores_array = np.array(results.normalised_scores)  # 👈 key fix
# avg_payoffs = scores_array.mean(axis=1)

# highest_avg_score = avg_payoffs.max()
# winner_strategy = strategy_names[avg_payoffs.argmax()]

# print("Highest average payoff:", highest_avg_score)
# print("Winning strategy:", winner_strategy)

In [23]:
df['Winning_strategy']=['FoolMeOnce','Opposite Grudger',
'Level Punisher','Fortress4','Level Punisher','Fortress4','Tricky Cooperator','Hard Go By Majority','Fortress3','Cooperator Hunter','Fortress4',
'Hard Go By Majority','Cooperator Hunter','Cooperator Hunter','GrudgerAlternator','Cooperator Hunter','Cooperator Hunter','Resurrection','Tricky Cooperator','Tricky Cooperator','Tricky Cooperator','Math Constant Hunter','Slow Tit For Two Tats 2',
'Suspicious Tit For Tat','Defector Hunter','EventualCycleHunter','BetterAndBetter','RandomHunter','TitFor2Tats','BetterAndBetter','CooperatorHunter',
'Fortress3','LevelPunisher','Bully','TitFor2Tats','Fortress3','CooperatorHunter','Appeaser','Fortress4','CooperatorHunter','Fortress4','Prober2',
'TitFor2Tats','FoolMeOnce','CooperatorHunter','LevelPunisher','FoolMeOnce','Handshake','HardTitForTat','CooperatorHunter',
'MathConstantHunter','MathConstantHunter','DefectorHunter','BetterAndBetter','AlternatorHunter','AlternatorHunter','Bully','MathConstantHunter',
'ForgetfulGrudger','SlowTitForTwoTats2','TrickyDefector','Appeaser','Fortress3','TitFor2Tats','Fortress3','CooperatorHunter','Fortress3','TitFor2Tats',
'Bully','Fortress4','CooperatorHunter','Fortress4','Fortress4','TitFor2Tats','TrickyCooperator','Winner12','LevelPunisher','LevelPunisher','Fortress4',
'Resurrection','TitFor2Tats','Appeaser','VeryBad','RandomHunter','Raider','EventualCycleHunter','AlternatorHunter','Fortress4','TrickyCooperator',
'TF3','NiceAverageCopier','BetterAndBetter','TrickyCooperator','OppositeGrudger','Winner12','Prober2','TrickyCooperator','Fortress4','GrudgerAlternator','CooperatorHunter']

In [25]:
df['Highest_avg_Score']=['2.49','3.65','2.46','3.53','2.34','3.21','2.45','2.38','2.40','3.02','2.51','2.60','2.38','2.38','2.45','2.43','2.36','2.31','2.42','2.38','2.42',
'2.40','2.40','3.64','3.09','2.80','3.09','2.44','2.40','2.82','2.54','3.64','2.50','3.47','2.33','3.17','2.48','2.34','2.39','3.15','2.49','2.50','2.49',
'2.43','2.49','2.42','2.33','2.34','2.47','2.44','2.38','2.42','2.41','3.61','3.14','2.77','3.19','2.42','2.38','2.38','2.74','2.48','3.62','2.55','3.48',
'2.34','3.14','2.43','2.35','2.40','3.09','2.50','2.58','2.49','2.44','2.44','2.42','2.30','2.31','2.45','2.47','2.37','2.43','2.41','3.63','3.12','2.82',
'3.16','2.43','2.37','2.36','2.78','2.49','3.61','2.50','3.45','2.32','3.18','2.53','2.48']

In [26]:
df.head()

,noise,player_1,player_10,player_103,player_106,player_107,player_108,player_109,player_11,player_111,...,player_75,player_79,player_85,player_9,probend,repetitions,size,turns,Winning_strategy,Highest_avg_Score
0,0.849486,Prober 2,Thumper,NaN,NaN,NaN,NaN,NaN,Fool Me Once,NaN,...,NaN,Predator,Fortress3,Level Punisher,0.895039,40.0,101.0,134.0,FoolMeOnce,2.49
1,0.040484,Prober 2,Thumper,NaN,NaN,NaN,NaN,NaN,Fool Me Once,NaN,...,NaN,Predator,Fortress3,Level Punisher,0.965465,63.0,101.0,99.0,Opposite Grudger,3.65
2,0.847434,Prober 2,Thumper,NaN,NaN,NaN,NaN,NaN,Fool Me Once,NaN,...,NaN,Predator,Fortress3,Level Punisher,0.763775,82.0,101.0,35.0,Level Punisher,2.46
3,0.084872,Prober 2,Thumper,NaN,NaN,NaN,NaN,NaN,Fool Me Once,NaN,...,NaN,Predator,Fortress3,Level Punisher,0.835499,21.0,101.0,15.0,Fortress4,3.53
4,0.544229,Prober 2,Thumper,NaN,NaN,NaN,NaN,NaN,Fool Me Once,NaN,...,NaN,Predator,Fortress3,Level Punisher,0.369955,85.0,101.0,61.0,Level Punisher,2.34